/** Quiet phone sign-in. Inputs are 12px, the continue button is the only pill. */
export const CLERK_APPEARANCE = {
  options: {
    elevation: "flush" as const,
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    logoPlacement: "none" as const,
    privacyPageUrl: "/privacy",
    termsPageUrl: "/terms",
    unsafe_disableDevelopmentModeWarnings: true,
    shimmer: false,
  },
  layout: {
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    logoPlacement: "none" as const,
    privacyPageUrl: "/privacy",
    termsPageUrl: "/terms",
    unsafe_disableDevelopmentModeWarnings: true,
    shimmer: false,
  },
  variables: {
    colorPrimary: "#2DD4BF",
    colorBackground: "#0B1F3A",
    colorNeutral: "#F7F8FA",
    colorText: "#F7F8FA",
    colorTextSecondary: "rgba(247,248,250,0.62)",
    colorTextOnPrimaryBackground: "#042F2E",
    colorInputBackground: "#0A182C",
    colorInputText: "#F7F8FA",
    colorDanger: "#FB7185",
    colorSuccess: "#2DD4BF",
    borderRadius: "12px",
    fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
    fontSize: "16px",
  },
  elements: {
    rootBox: "bb-clerk-root w-full max-w-full",
    card: "bb-clerk-card w-full max-w-full border-0 bg-transparent p-0 shadow-none ring-0",
    cardBox: "bb-clerk-cardbox w-full max-w-full shadow-none",
    main: "bb-clerk-main w-full max-w-full",
    header: "hidden",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    logoBox: "hidden",
    logoImage: "hidden",
    footer: "hidden",
    footerAction: "hidden",
    footerActionText: "hidden",
    footerActionLink: "hidden",
    footerPages: "hidden",
    footerPagesLink: "hidden",
    badge: "hidden",
    formFieldLabel: "text-[13px] font-medium text-white/70",
    formFieldInput:
      "h-12 rounded-xl border-0 bg-[#0A182C] px-4 text-base text-[#F7F8FA] ring-1 ring-white/15 placeholder:text-white/35",
    formButtonPrimary:
      "h-12 w-full rounded-full bg-[#2DD4BF] text-[#042F2E] shadow-none hover:bg-[#5EEAD4]",
    socialButtonsBlockButton:
      "h-12 rounded-xl bg-[#163556] text-[#F7F8FA] shadow-none ring-1 ring-white/15",
    socialButtonsBlockButtonText: "text-[#F7F8FA] font-medium",
    dividerLine: "bg-white/12",
    dividerText: "text-[12px] text-white/40",
    formFieldInputShowPasswordButton: "text-white/50",
    identityPreview: "bg-transparent ring-1 ring-white/15",
    identityPreviewText: "text-[#F7F8FA]",
    identityPreviewEditButton: "text-[#5EEAD4]",
    formFieldErrorText: "text-[#fb7185]",
    alert: "rounded-xl bg-white/[0.06] text-[#F7F8FA] ring-1 ring-white/12",
  },
};
