/** Quiet Capital Clerk chrome — appearance API only. Soft-signal HOLD. */
export const CLERK_APPEARANCE = {
  options: {
    elevation: "flush" as const,
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    logoPlacement: "inside" as const,
    privacyPageUrl: "/privacy",
    termsPageUrl: "/terms",
    unsafe_disableDevelopmentModeWarnings: true,
    shimmer: false,
  },
  layout: {
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    logoPlacement: "inside" as const,
    privacyPageUrl: "/privacy",
    termsPageUrl: "/terms",
    unsafe_disableDevelopmentModeWarnings: true,
    shimmer: false,
  },
  variables: {
    colorPrimary: "#2DD4BF",
    colorBackground: "#122A46",
    colorNeutral: "#F7F8FA",
    colorText: "#F7F8FA",
    colorTextSecondary: "rgba(247,248,250,0.68)",
    colorTextOnPrimaryBackground: "#042F2E",
    colorInputBackground: "rgba(255,255,255,0.06)",
    colorInputText: "#F7F8FA",
    colorDanger: "#E11D48",
    colorSuccess: "#059669",
    borderRadius: "999px",
    fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
    fontSize: "15px",
  },
  elements: {
    rootBox: "bb-clerk-root w-full max-w-full",
    card: "bb-clerk-card w-full max-w-full border-0 bg-transparent p-0 shadow-none ring-0",
    cardBox: "bb-clerk-cardbox w-full max-w-full overflow-hidden shadow-none",
    main: "bb-clerk-main w-full max-w-full",
    header: "hidden",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    logoBox: "hidden",
    logoImage: "hidden",
    footer: "hidden",
    footerAction: "hidden",
    footerActionText: "hidden",
    footerActionLink: "hidden",
    footerPages: "hidden",
    footerPagesLink: "hidden",
    formFieldLabel: "text-[13px] font-medium text-white/75",
    formFieldInput:
      "h-12 rounded-full border-0 bg-white/[0.06] px-5 text-[15px] text-[#F7F8FA] ring-1 ring-white/12 placeholder:text-white/35",
    formButtonPrimary:
      "h-12 w-full rounded-full bg-[#2DD4BF] text-[#042F2E] shadow-none hover:bg-[#5EEAD4]",
    socialButtonsBlockButton:
      "h-12 rounded-full bg-white/[0.06] text-[#F7F8FA] shadow-none ring-1 ring-white/12 hover:bg-white/[0.1]",
    socialButtonsBlockButtonText: "text-[#F7F8FA]",
    dividerLine: "bg-white/15",
    dividerText: "text-white/45",
    formFieldInputShowPasswordButton: "text-white/50",
    identityPreview: "bg-transparent ring-1 ring-white/12",
    identityPreviewText: "text-[#F7F8FA]",
    identityPreviewEditButton: "text-[#2DD4BF]",
    formFieldErrorText: "text-[#fb7185]",
    alert: "bg-white/[0.06] text-[#F7F8FA] ring-1 ring-white/12",
  },
};
